### ISSUE TITLE
Keyswitch footprints change in the middle of the guide

### ISSUE THREAD

**Issue by flexd** [ruiqimao/keyboard-pcb-guide#18]
Hey.

When you first put the components on the PCB, the keyswitches do not have pins to put the diode in between. In the next screenshot they do. Clearly the footprint used in the tutorial earlier is not the correct one, but which one do I want to use?

**Comment by flexd** [comment]
See 
![image](https://user-images.githubusercontent.com/2317/63924542-be428f80-ca48-11e9-9d08-9e3f8bc8b84f.png) and 
![image](https://user-images.githubusercontent.com/2317/63924558-c3074380-ca48-11e9-8b91-dd7aeabe6968.png)

**Comment by MacroLens** [comment]
I don't really see the problem? You just have to place the diode on the opposite side of the key switch and use vias to connect them up. The footprint never changed?

What do you mean the key switches don't have pins to put the diodes between?

**Comment by flexd** [comment]
I just noticed it when reading the guide. For someone new to creating PCBs like this it was confusing, I thought I missed a step or perhaps had the wrong component. I ended up using another component instead from a guide that was basically this one updated to KiCad 5. :-)

![image](https://user-images.githubusercontent.com/2317/64131057-6ef0bc00-cdc6-11e9-8ae3-d79bf29de0ed.png)

**Comment by somayn** [comment]
> I just noticed it when reading the guide. For someone new to creating PCBs like this it was confusing, I thought I missed a step or perhaps had the wrong component. I ended up using another component instead from a guide that was basically this one updated to KiCad 5. :-)
> 
> ![image](https://user-images.githubusercontent.com/2317/64131057-6ef0bc00-cdc6-11e9-8ae3-d79bf29de0ed.png)

@flexd could you tell me which kicad 5 guide you are talking about?

**Comment by flexd** [comment]
> > I just noticed it when reading the guide. For someone new to creating PCBs like this it was confusing, I thought I missed a step or perhaps had the wrong component. I ended up using another component instead from a guide that was basically this one updated to KiCad 5. :-)
> > ![image](https://user-images.githubusercontent.com/2317/64131057-6ef0bc00-cdc6-11e9-8ae3-d79bf29de0ed.png)
> 
> @flexd could you tell me which kicad 5 guide you are talking about?
https://wiki.ai03.me/books/pcb-design/page/pcb-guide-part-1---preparations
