### ISSUE TITLE
Tutorial for lighting

### ISSUE THREAD

**Issue by help-14** [ruiqimao/keyboard-pcb-guide#2]
Hi, is there any plan on tutorial for lighting?

**Comment by amnobis** [comment]
By lighting do you mean per switch LED or underglow for the board? Or both?

**Comment by help-14** [comment]
per switch led :D

**Comment by ruiqimao** [comment]
No plan for that. That requires the use of an LED controller, which is not supported by QMK and a bit too advanced for a beginner's guide.

**Comment by GeeWizWow** [comment]
hey ruiqimao 

underglow would be nice touch, lots of boards seem to use smd ws2812 s
